# Generated by Django 3.2.5 on 2021-07-31 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypesOfPlaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('ty', models.ManyToManyField(to='getdist.TypesOfPlaces')),
            ],
        ),
    ]
