# Generated by Django 3.2.5 on 2021-08-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdist', '0004_auto_20210731_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='style',
            field=models.CharField(default='_', max_length=1000),
        ),
    ]
