# Generated by Django 3.2.5 on 2021-08-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdist', '0005_question_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='previous',
            field=models.BooleanField(default=False),
        ),
    ]
