# Generated by Django 3.2.5 on 2021-08-02 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdist', '0006_question_previous'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchservices',
            name='name',
            field=models.CharField(default='_', max_length=5000),
        ),
    ]
